[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib/lib.rs"

[[bin]]
name = "2015-01"
path = "src/2015/day01.rs"

[[bin]]
name = "2015-02"
path = "src/2015/day02.rs"

[[bin]]
name = "2015-03"
path = "src/2015/day03.rs"

[[bin]]
name = "2015-04"
path = "src/2015/day04.rs"

[[bin]]
name = "2015-05"
path = "src/2015/day05.rs"

[[bin]]
name = "2015-06"
path = "src/2015/day06.rs"

[[bin]]
name = "2015-07"
path = "src/2015/day07.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
md5 = "0.7.0"
ndarray = "0.15.6"
nom = "7.1.3"
