[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib/lib.rs"

[[bin]]
name = "2015-01"
path = "src/2015/day01.rs"

[[bin]]
name = "2015-02"
path = "src/2015/day02.rs"

[[bin]]
name = "2015-03"
path = "src/2015/day03.rs"

[[bin]]
name = "2015-04"
path = "src/2015/day04.rs"

[[bin]]
name = "2015-05"
path = "src/2015/day05.rs"

[[bin]]
name = "2015-06"
path = "src/2015/day06.rs"

[[bin]]
name = "2015-07"
path = "src/2015/day07.rs"

[[bin]]
name = "2017-01"
path = "src/2017/day01.rs"

[[bin]]
name = "2017-02"
path = "src/2017/day02.rs"

[[bin]]
name = "2017-03"
path = "src/2017/day03.rs"

[[bin]]
name = "2017-04"
path = "src/2017/day04.rs"

[[bin]]
name = "2017-05"
path = "src/2017/day05.rs"

[[bin]]
name = "2017-06"
path = "src/2017/day06.rs"

[[bin]]
name = "2017-07"
path = "src/2017/day07.rs"

[[bin]]
name = "2017-08"
path = "src/2017/day08.rs"

[[bin]]
name = "2017-09"
path = "src/2017/day09.rs"

[[bin]]
name = "2017-10"
path = "src/2017/day10.rs"

[[bin]]
name = "2017-11"
path = "src/2017/day11.rs"

[[bin]]
name = "2017-12"
path = "src/2017/day12.rs"

[[bin]]
name = "2017-13"
path = "src/2017/day13.rs"

[[bin]]
name = "2017-14"
path = "src/2017/day14.rs"

[[bin]]
name = "2017-15"
path = "src/2017/day15.rs"

[[bin]]
name = "2017-16"
path = "src/2017/day16.rs"

[[bin]]
name = "2017-17"
path = "src/2017/day17.rs"

[[bin]]
name = "2017-18"
path = "src/2017/day18.rs"

[[bin]]
name = "2017-19"
path = "src/2017/day19.rs"

[[bin]]
name = "2017-20"
path = "src/2017/day20.rs"

[[bin]]
name = "2023-01"
path = "src/2023/day01.rs"

[[bin]]
name = "2023-02"
path = "src/2023/day02.rs"

[[bin]]
name = "2023-23"
path = "src/2023/day23.rs"

[[bin]]
name = "2023-25"
path = "src/2023/day25.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
md5 = "0.7.0"
nom = "7.1.3"
petgraph = "0.6.4"